### ISSUE TITLE
IP v6 is not working, ipv6.icanhazip service is down

### ISSUE THREAD

**Issue by LazaroOnline** [sindresorhus/public-ip#40]
Cannot get IP v6, the service
https://ipv6.icanhazip.com/
seems down, or maybe it was moved, anyhow this library is not working for v6 anymore following the examples.
The browser displays this error:
ipv6.icanhazip.com’s server IP address could not be found.
Maybe the service maintainers deleted the DNS for the "ipv6" subdomain.

IP v4 does work.

Testing code: 
```js
const publicIp = require('public-ip');
(async () => {
	console.log(await publicIp.v6());
})();
```
public-ip version: 3.2.0
I submited the issue to `major/icanhaz` [here](https://github.com/major/icanhaz/issues/14).

**Comment by ghostnumber7** [comment]
Probably you are seeing the same issue I see from my computer, the resolver I'm using can't find the host because it's using A records to resolve and no A record is defined on `ipv6.icanhazip.com`, only AAAA records are. I tested from some online services to see if it was actually working and it seems to be.

![image](https://user-images.githubusercontent.com/1007398/68961280-c7720b80-07b0-11ea-820c-388c24635264.png)

![image](https://user-images.githubusercontent.com/1007398/68959485-e40c4480-07ac-11ea-9018-bb15aa87b97c.png)

![image](https://user-images.githubusercontent.com/1007398/68959558-04d49a00-07ad-11ea-9bf7-94e9030b61f9.png)

![image](https://user-images.githubusercontent.com/1007398/68960493-0606c680-07af-11ea-8193-dc592bfb3f51.png)

![image](https://user-images.githubusercontent.com/1007398/68960894-d99f7a00-07af-11ea-91b2-f413ef1b192d.png)

![image](https://user-images.githubusercontent.com/1007398/68960876-d1473f00-07af-11ea-97dd-4a9915f477ed.png)

**Comment by sindresorhus** [comment]
https://ipv6.icanhazip.com/ loads fine for me.

**Comment by LazaroOnline** [comment]
I tried from a home network, office network, phone 4G network, all with the same `ERR_NAME_NOT_RESOLVED` error.

If it is a network configuration error, does anyone knows how to solve it or how to make it work?
Also if this is normal then it would be nice to add a note in `readme.md` near the `usage` section to alert the users.

**Comment by sindresorhus** [comment]
@LazaroOnline Do you actually have a IPv6 connection? Test here: https://ipv6-test.com

**Comment by LazaroOnline** [comment]
It seems I only have IPv4, but I don't know if it is a problem with the router, my device, my ISP...

https://ipv6-test.com restuls:
### IPv4 connectivity:
* IPv4: Supported
* ... _(other fields with it's IPv4 values setted)_
### IPv6 connectivity:
* IPv6: Not supported
* the rest of IPv6 fields are shown empty.
* Score: 4/20
### Browser:
* Default: IPv4
* Fallback: No
### DNS:
* DNS4 + IP6: Unreachable
* DNS6 + IP4: Reachable
* DNS6 + IP6: Unreachable

**Comment by sindresorhus** [comment]
Closing as there's nothing for us to fix.
